http:
 host: "![NgdyhU8HAgs/ADBSG/eyzQ==]"
 port: "![mBi86+xaCbd7gF+uaZaGwQ==]"
 readTimeout: "![5V7R9zTWsLd0kcAF9+6s/w==]"
 connectionTimeout: "![EIaAWO/K2r7WnAZoYhLzPQ==]"
 retryFrequency: "![hf/bk+8A4F4h+YczhAph5A==]"
 retryAttempt: "![Ov8PC9nM5sVu6x3ULCnP9g==]"